// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: bitway/dlc/params.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	_ "google.golang.org/protobuf/types/known/durationpb"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Params defines the parameters for the module.
type Params struct {
	NonceQueueSize             uint32   `protobuf:"varint,1,opt,name=nonce_queue_size,json=nonceQueueSize,proto3" json:"nonce_queue_size,omitempty"`
	NonceGenerationBatchSize   uint32   `protobuf:"varint,2,opt,name=nonce_generation_batch_size,json=nonceGenerationBatchSize,proto3" json:"nonce_generation_batch_size,omitempty"`
	NonceGenerationInterval    int64    `protobuf:"varint,3,opt,name=nonce_generation_interval,json=nonceGenerationInterval,proto3" json:"nonce_generation_interval,omitempty"`
	AllowedOracleParticipants  []string `protobuf:"bytes,4,rep,name=allowed_oracle_participants,json=allowedOracleParticipants,proto3" json:"allowed_oracle_participants,omitempty"`
	OracleParticipantNum       uint32   `protobuf:"varint,5,opt,name=oracle_participant_num,json=oracleParticipantNum,proto3" json:"oracle_participant_num,omitempty"`
	OracleParticipantThreshold uint32   `protobuf:"varint,6,opt,name=oracle_participant_threshold,json=oracleParticipantThreshold,proto3" json:"oracle_participant_threshold,omitempty"`
}

func (m *Params) Reset()         { *m = Params{} }
func (m *Params) String() string { return proto.CompactTextString(m) }
func (*Params) ProtoMessage()    {}
func (*Params) Descriptor() ([]byte, []int) {
	return fileDescriptor_d822f0c38f6df9df, []int{0}
}
func (m *Params) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Params.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Params) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Params.Merge(m, src)
}
func (m *Params) XXX_Size() int {
	return m.Size()
}
func (m *Params) XXX_DiscardUnknown() {
	xxx_messageInfo_Params.DiscardUnknown(m)
}

var xxx_messageInfo_Params proto.InternalMessageInfo

func (m *Params) GetNonceQueueSize() uint32 {
	if m != nil {
		return m.NonceQueueSize
	}
	return 0
}

func (m *Params) GetNonceGenerationBatchSize() uint32 {
	if m != nil {
		return m.NonceGenerationBatchSize
	}
	return 0
}

func (m *Params) GetNonceGenerationInterval() int64 {
	if m != nil {
		return m.NonceGenerationInterval
	}
	return 0
}

func (m *Params) GetAllowedOracleParticipants() []string {
	if m != nil {
		return m.AllowedOracleParticipants
	}
	return nil
}

func (m *Params) GetOracleParticipantNum() uint32 {
	if m != nil {
		return m.OracleParticipantNum
	}
	return 0
}

func (m *Params) GetOracleParticipantThreshold() uint32 {
	if m != nil {
		return m.OracleParticipantThreshold
	}
	return 0
}

func init() {
	proto.RegisterType((*Params)(nil), "bitway.dlc.Params")
}

func init() { proto.RegisterFile("bitway/dlc/params.proto", fileDescriptor_d822f0c38f6df9df) }

var fileDescriptor_d822f0c38f6df9df = []byte{
	// 354 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x92, 0xcf, 0x4a, 0xeb, 0x40,
	0x14, 0x87, 0x9b, 0xf6, 0xde, 0xc2, 0x1d, 0xb8, 0x97, 0x4b, 0x28, 0x36, 0x6d, 0x25, 0x14, 0x57,
	0x59, 0x35, 0x0b, 0x5d, 0x09, 0x8a, 0x74, 0x23, 0x6e, 0xb4, 0x56, 0x57, 0x6e, 0xc2, 0x64, 0x32,
	0x26, 0x03, 0x93, 0x39, 0x71, 0xfe, 0x58, 0xdb, 0xa7, 0xf0, 0xb1, 0x5c, 0x76, 0xe9, 0x52, 0x5a,
	0x7c, 0x0f, 0xe9, 0x4c, 0x14, 0x69, 0xdd, 0x9d, 0x73, 0x7e, 0xdf, 0xc7, 0x19, 0x38, 0x83, 0xba,
	0x29, 0xd3, 0x33, 0x3c, 0x8f, 0x33, 0x4e, 0xe2, 0x0a, 0x4b, 0x5c, 0xaa, 0x51, 0x25, 0x41, 0x83,
	0x8f, 0x5c, 0x30, 0xca, 0x38, 0xe9, 0x77, 0x72, 0xc8, 0xc1, 0x8e, 0xe3, 0x4d, 0xe5, 0x88, 0x7e,
	0x98, 0x03, 0xe4, 0x9c, 0xc6, 0xb6, 0x4b, 0xcd, 0x7d, 0x9c, 0x19, 0x89, 0x35, 0x03, 0x51, 0xe7,
	0x3d, 0x02, 0xaa, 0x04, 0x95, 0x38, 0xd1, 0x35, 0x2e, 0x3a, 0x78, 0x6f, 0xa2, 0xf6, 0xc4, 0x6e,
	0xf3, 0x23, 0xf4, 0x5f, 0x80, 0x20, 0x34, 0x79, 0x30, 0xd4, 0xd0, 0x44, 0xb1, 0x05, 0x0d, 0xbc,
	0xa1, 0x17, 0xfd, 0x9d, 0xfe, 0xb3, 0xf3, 0xeb, 0xcd, 0xf8, 0x86, 0x2d, 0xa8, 0x7f, 0x82, 0x06,
	0x8e, 0xcc, 0xa9, 0xa0, 0x6e, 0x53, 0x92, 0x62, 0x4d, 0x0a, 0x27, 0x35, 0xad, 0x14, 0x58, 0xe4,
	0xfc, 0x8b, 0x18, 0x6f, 0x00, 0xab, 0x1f, 0xa3, 0xde, 0x8e, 0xce, 0x84, 0xa6, 0xf2, 0x11, 0xf3,
	0xa0, 0x35, 0xf4, 0xa2, 0xd6, 0xb4, 0xbb, 0x25, 0x5f, 0xd4, 0xb1, 0x7f, 0x8a, 0x06, 0x98, 0x73,
	0x98, 0xd1, 0x2c, 0x01, 0x89, 0x09, 0xa7, 0x49, 0x85, 0xa5, 0x66, 0x84, 0x55, 0x58, 0x68, 0x15,
	0xfc, 0x1a, 0xb6, 0xa2, 0x3f, 0xd3, 0x5e, 0x8d, 0x5c, 0x59, 0x62, 0xf2, 0x0d, 0xf0, 0x8f, 0xd0,
	0xde, 0xae, 0x97, 0x08, 0x53, 0x06, 0xbf, 0xed, 0xab, 0x3b, 0xb0, 0xed, 0x5c, 0x9a, 0xd2, 0x3f,
	0x43, 0xfb, 0x3f, 0x58, 0xba, 0x90, 0x54, 0x15, 0xc0, 0xb3, 0xa0, 0x6d, 0xdd, 0xfe, 0x8e, 0x7b,
	0xfb, 0x49, 0x8c, 0xc7, 0x2f, 0xab, 0xd0, 0x5b, 0xae, 0x42, 0xef, 0x6d, 0x15, 0x7a, 0xcf, 0xeb,
	0xb0, 0xb1, 0x5c, 0x87, 0x8d, 0xd7, 0x75, 0xd8, 0xb8, 0x8b, 0x72, 0xa6, 0x0b, 0x93, 0x8e, 0x08,
	0x94, 0xb1, 0xbb, 0x34, 0xc7, 0xa9, 0xaa, 0xcb, 0xf8, 0xc9, 0xfe, 0x07, 0x3d, 0xaf, 0xa8, 0x4a,
	0xdb, 0xf6, 0x64, 0x87, 0x1f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x34, 0xfa, 0x42, 0x4e, 0x2a, 0x02,
	0x00, 0x00,
}

func (m *Params) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Params) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Params) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.OracleParticipantThreshold != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.OracleParticipantThreshold))
		i--
		dAtA[i] = 0x30
	}
	if m.OracleParticipantNum != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.OracleParticipantNum))
		i--
		dAtA[i] = 0x28
	}
	if len(m.AllowedOracleParticipants) > 0 {
		for iNdEx := len(m.AllowedOracleParticipants) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.AllowedOracleParticipants[iNdEx])
			copy(dAtA[i:], m.AllowedOracleParticipants[iNdEx])
			i = encodeVarintParams(dAtA, i, uint64(len(m.AllowedOracleParticipants[iNdEx])))
			i--
			dAtA[i] = 0x22
		}
	}
	if m.NonceGenerationInterval != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.NonceGenerationInterval))
		i--
		dAtA[i] = 0x18
	}
	if m.NonceGenerationBatchSize != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.NonceGenerationBatchSize))
		i--
		dAtA[i] = 0x10
	}
	if m.NonceQueueSize != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.NonceQueueSize))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintParams(dAtA []byte, offset int, v uint64) int {
	offset -= sovParams(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Params) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.NonceQueueSize != 0 {
		n += 1 + sovParams(uint64(m.NonceQueueSize))
	}
	if m.NonceGenerationBatchSize != 0 {
		n += 1 + sovParams(uint64(m.NonceGenerationBatchSize))
	}
	if m.NonceGenerationInterval != 0 {
		n += 1 + sovParams(uint64(m.NonceGenerationInterval))
	}
	if len(m.AllowedOracleParticipants) > 0 {
		for _, s := range m.AllowedOracleParticipants {
			l = len(s)
			n += 1 + l + sovParams(uint64(l))
		}
	}
	if m.OracleParticipantNum != 0 {
		n += 1 + sovParams(uint64(m.OracleParticipantNum))
	}
	if m.OracleParticipantThreshold != 0 {
		n += 1 + sovParams(uint64(m.OracleParticipantThreshold))
	}
	return n
}

func sovParams(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozParams(x uint64) (n int) {
	return sovParams(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Params) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowParams
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Params: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Params: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field NonceQueueSize", wireType)
			}
			m.NonceQueueSize = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.NonceQueueSize |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field NonceGenerationBatchSize", wireType)
			}
			m.NonceGenerationBatchSize = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.NonceGenerationBatchSize |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field NonceGenerationInterval", wireType)
			}
			m.NonceGenerationInterval = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.NonceGenerationInterval |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AllowedOracleParticipants", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AllowedOracleParticipants = append(m.AllowedOracleParticipants, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field OracleParticipantNum", wireType)
			}
			m.OracleParticipantNum = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.OracleParticipantNum |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field OracleParticipantThreshold", wireType)
			}
			m.OracleParticipantThreshold = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.OracleParticipantThreshold |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipParams(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthParams
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipParams(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowParams
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthParams
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupParams
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthParams
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthParams        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowParams          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupParams = fmt.Errorf("proto: unexpected end of group")
)
