// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: bitway/btcbridge/genesis.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// GenesisState defines the btc bridge module's genesis state.
type GenesisState struct {
	Params                     Params                  `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
	Utxos                      []*UTXO                 `protobuf:"bytes,2,rep,name=utxos,proto3" json:"utxos,omitempty"`
	DkgRequests                []*DKGRequest           `protobuf:"bytes,3,rep,name=dkg_requests,json=dkgRequests,proto3" json:"dkg_requests,omitempty"`
	DkgCompletions             []*DKGCompletionRequest `protobuf:"bytes,4,rep,name=dkg_completions,json=dkgCompletions,proto3" json:"dkg_completions,omitempty"`
	SigningRequests            []*SigningRequest       `protobuf:"bytes,5,rep,name=signing_requests,json=signingRequests,proto3" json:"signing_requests,omitempty"`
	WithdrawRequests           []*WithdrawRequest      `protobuf:"bytes,6,rep,name=withdraw_requests,json=withdrawRequests,proto3" json:"withdraw_requests,omitempty"`
	PendingBtcWithdrawRequests []*WithdrawRequest      `protobuf:"bytes,7,rep,name=pending_btc_withdraw_requests,json=pendingBtcWithdrawRequests,proto3" json:"pending_btc_withdraw_requests,omitempty"`
	MintedTxHashes             []string                `protobuf:"bytes,8,rep,name=minted_tx_hashes,json=mintedTxHashes,proto3" json:"minted_tx_hashes,omitempty"`
}

func (m *GenesisState) Reset()         { *m = GenesisState{} }
func (m *GenesisState) String() string { return proto.CompactTextString(m) }
func (*GenesisState) ProtoMessage()    {}
func (*GenesisState) Descriptor() ([]byte, []int) {
	return fileDescriptor_8f3a94b884470b49, []int{0}
}
func (m *GenesisState) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GenesisState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GenesisState.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GenesisState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenesisState.Merge(m, src)
}
func (m *GenesisState) XXX_Size() int {
	return m.Size()
}
func (m *GenesisState) XXX_DiscardUnknown() {
	xxx_messageInfo_GenesisState.DiscardUnknown(m)
}

var xxx_messageInfo_GenesisState proto.InternalMessageInfo

func (m *GenesisState) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

func (m *GenesisState) GetUtxos() []*UTXO {
	if m != nil {
		return m.Utxos
	}
	return nil
}

func (m *GenesisState) GetDkgRequests() []*DKGRequest {
	if m != nil {
		return m.DkgRequests
	}
	return nil
}

func (m *GenesisState) GetDkgCompletions() []*DKGCompletionRequest {
	if m != nil {
		return m.DkgCompletions
	}
	return nil
}

func (m *GenesisState) GetSigningRequests() []*SigningRequest {
	if m != nil {
		return m.SigningRequests
	}
	return nil
}

func (m *GenesisState) GetWithdrawRequests() []*WithdrawRequest {
	if m != nil {
		return m.WithdrawRequests
	}
	return nil
}

func (m *GenesisState) GetPendingBtcWithdrawRequests() []*WithdrawRequest {
	if m != nil {
		return m.PendingBtcWithdrawRequests
	}
	return nil
}

func (m *GenesisState) GetMintedTxHashes() []string {
	if m != nil {
		return m.MintedTxHashes
	}
	return nil
}

func init() {
	proto.RegisterType((*GenesisState)(nil), "bitway.btcbridge.GenesisState")
}

func init() { proto.RegisterFile("bitway/btcbridge/genesis.proto", fileDescriptor_8f3a94b884470b49) }

var fileDescriptor_8f3a94b884470b49 = []byte{
	// 414 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x92, 0x41, 0x6b, 0xd4, 0x40,
	0x14, 0xc7, 0x13, 0x77, 0xbb, 0xea, 0x6c, 0x69, 0xe3, 0x20, 0x12, 0x82, 0x8d, 0xd1, 0x83, 0xe4,
	0x20, 0x09, 0x54, 0xf0, 0x2a, 0xac, 0x42, 0x0b, 0x05, 0x2b, 0x69, 0xa5, 0xe2, 0x25, 0x24, 0x99,
	0x61, 0x32, 0x6c, 0x93, 0x89, 0x79, 0xb3, 0x24, 0xfd, 0x16, 0x7e, 0x17, 0xbf, 0x44, 0x8f, 0x3d,
	0x7a, 0x12, 0xd9, 0xfd, 0x22, 0xb2, 0x33, 0xd9, 0xed, 0xee, 0xc6, 0x83, 0xb7, 0x37, 0xef, 0xff,
	0x7b, 0xbf, 0x79, 0x87, 0x87, 0xdc, 0x94, 0xcb, 0x26, 0xb9, 0x09, 0x53, 0x99, 0xa5, 0x35, 0x27,
	0x8c, 0x86, 0x8c, 0x96, 0x14, 0x38, 0x04, 0x55, 0x2d, 0xa4, 0xc0, 0x96, 0xce, 0x83, 0x75, 0xee,
	0x3c, 0x65, 0x82, 0x09, 0x15, 0x86, 0xcb, 0x4a, 0x73, 0xce, 0x51, 0xcf, 0x53, 0x25, 0x75, 0x52,
	0x74, 0x1a, 0xc7, 0xeb, 0xc5, 0xeb, 0x4a, 0x13, 0xaf, 0x7e, 0x0e, 0xd1, 0xfe, 0x89, 0xfe, 0xfa,
	0x42, 0x26, 0x92, 0xe2, 0x77, 0x68, 0xa4, 0x15, 0xb6, 0xe9, 0x99, 0xfe, 0xf8, 0xd8, 0x0e, 0x76,
	0x57, 0x09, 0x3e, 0xab, 0x7c, 0x32, 0xbc, 0xfd, 0xfd, 0xc2, 0x88, 0x3a, 0x1a, 0xbf, 0x41, 0x7b,
	0x33, 0xd9, 0x0a, 0xb0, 0x1f, 0x78, 0x03, 0x7f, 0x7c, 0xfc, 0xac, 0x3f, 0xf6, 0xe5, 0xf2, 0xeb,
	0x79, 0xa4, 0x21, 0xfc, 0x1e, 0xed, 0x93, 0x29, 0x8b, 0x6b, 0xfa, 0x7d, 0x46, 0x41, 0x82, 0x3d,
	0x50, 0x43, 0xcf, 0xfb, 0x43, 0x1f, 0xcf, 0x4e, 0x22, 0x0d, 0x45, 0x63, 0x32, 0x65, 0x5d, 0x0d,
	0xf8, 0x1c, 0x1d, 0x2e, 0x05, 0x99, 0x28, 0xaa, 0x6b, 0x2a, 0xb9, 0x28, 0xc1, 0x1e, 0x2a, 0xc7,
	0xeb, 0x7f, 0x3a, 0x3e, 0xac, 0xb9, 0x95, 0xed, 0x80, 0x4c, 0xd9, 0x7d, 0x17, 0xf0, 0x19, 0xb2,
	0x80, 0xb3, 0x92, 0x97, 0x1b, 0x5b, 0xed, 0x29, 0xa3, 0xd7, 0x37, 0x5e, 0x68, 0x72, 0xe5, 0x3a,
	0x84, 0xad, 0x37, 0xe0, 0x4f, 0xe8, 0x49, 0xc3, 0x65, 0x4e, 0xea, 0xa4, 0xb9, 0xb7, 0x8d, 0x94,
	0xed, 0x65, 0xdf, 0x76, 0xd5, 0xa1, 0x2b, 0x9d, 0xd5, 0x6c, 0x37, 0x00, 0x13, 0x74, 0x54, 0xd1,
	0x92, 0x2c, 0x97, 0x4b, 0x65, 0x16, 0xf7, 0xdd, 0x0f, 0xff, 0xd7, 0xed, 0x74, 0x9e, 0x89, 0xcc,
	0xae, 0x76, 0x7f, 0xf1, 0x91, 0x55, 0xf0, 0x52, 0x52, 0x12, 0xcb, 0x36, 0xce, 0x13, 0xc8, 0x29,
	0xd8, 0x8f, 0xbc, 0x81, 0xff, 0x38, 0x3a, 0xd0, 0xfd, 0xcb, 0xf6, 0x54, 0x75, 0x27, 0xa7, 0xb7,
	0x73, 0xd7, 0xbc, 0x9b, 0xbb, 0xe6, 0x9f, 0xb9, 0x6b, 0xfe, 0x58, 0xb8, 0xc6, 0xdd, 0xc2, 0x35,
	0x7e, 0x2d, 0x5c, 0xe3, 0x5b, 0xc0, 0xb8, 0xcc, 0x67, 0x69, 0x90, 0x89, 0x22, 0xd4, 0xcb, 0x5c,
	0x27, 0x29, 0x74, 0x65, 0xd8, 0x6e, 0x5c, 0xa2, 0xbc, 0xa9, 0x28, 0xa4, 0x23, 0x75, 0x86, 0x6f,
	0xff, 0x06, 0x00, 0x00, 0xff, 0xff, 0x1c, 0x0c, 0x17, 0xc1, 0x11, 0x03, 0x00, 0x00,
}

func (m *GenesisState) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GenesisState) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GenesisState) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.MintedTxHashes) > 0 {
		for iNdEx := len(m.MintedTxHashes) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.MintedTxHashes[iNdEx])
			copy(dAtA[i:], m.MintedTxHashes[iNdEx])
			i = encodeVarintGenesis(dAtA, i, uint64(len(m.MintedTxHashes[iNdEx])))
			i--
			dAtA[i] = 0x42
		}
	}
	if len(m.PendingBtcWithdrawRequests) > 0 {
		for iNdEx := len(m.PendingBtcWithdrawRequests) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.PendingBtcWithdrawRequests[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x3a
		}
	}
	if len(m.WithdrawRequests) > 0 {
		for iNdEx := len(m.WithdrawRequests) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.WithdrawRequests[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x32
		}
	}
	if len(m.SigningRequests) > 0 {
		for iNdEx := len(m.SigningRequests) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.SigningRequests[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x2a
		}
	}
	if len(m.DkgCompletions) > 0 {
		for iNdEx := len(m.DkgCompletions) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.DkgCompletions[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x22
		}
	}
	if len(m.DkgRequests) > 0 {
		for iNdEx := len(m.DkgRequests) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.DkgRequests[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x1a
		}
	}
	if len(m.Utxos) > 0 {
		for iNdEx := len(m.Utxos) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Utxos[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenesis(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func encodeVarintGenesis(dAtA []byte, offset int, v uint64) int {
	offset -= sovGenesis(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *GenesisState) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovGenesis(uint64(l))
	if len(m.Utxos) > 0 {
		for _, e := range m.Utxos {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.DkgRequests) > 0 {
		for _, e := range m.DkgRequests {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.DkgCompletions) > 0 {
		for _, e := range m.DkgCompletions {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.SigningRequests) > 0 {
		for _, e := range m.SigningRequests {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.WithdrawRequests) > 0 {
		for _, e := range m.WithdrawRequests {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.PendingBtcWithdrawRequests) > 0 {
		for _, e := range m.PendingBtcWithdrawRequests {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.MintedTxHashes) > 0 {
		for _, s := range m.MintedTxHashes {
			l = len(s)
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	return n
}

func sovGenesis(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozGenesis(x uint64) (n int) {
	return sovGenesis(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *GenesisState) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GenesisState: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GenesisState: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Utxos", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Utxos = append(m.Utxos, &UTXO{})
			if err := m.Utxos[len(m.Utxos)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DkgRequests", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DkgRequests = append(m.DkgRequests, &DKGRequest{})
			if err := m.DkgRequests[len(m.DkgRequests)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DkgCompletions", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DkgCompletions = append(m.DkgCompletions, &DKGCompletionRequest{})
			if err := m.DkgCompletions[len(m.DkgCompletions)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SigningRequests", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SigningRequests = append(m.SigningRequests, &SigningRequest{})
			if err := m.SigningRequests[len(m.SigningRequests)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field WithdrawRequests", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.WithdrawRequests = append(m.WithdrawRequests, &WithdrawRequest{})
			if err := m.WithdrawRequests[len(m.WithdrawRequests)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PendingBtcWithdrawRequests", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PendingBtcWithdrawRequests = append(m.PendingBtcWithdrawRequests, &WithdrawRequest{})
			if err := m.PendingBtcWithdrawRequests[len(m.PendingBtcWithdrawRequests)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MintedTxHashes", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MintedTxHashes = append(m.MintedTxHashes, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipGenesis(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthGenesis
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupGenesis
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthGenesis
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthGenesis        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowGenesis          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupGenesis = fmt.Errorf("proto: unexpected end of group")
)
