// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: bitway/liquidation/params.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Params defines the parameters for the module.
type Params struct {
	// minimum liquidation factor permille
	MinLiquidationFactor uint32 `protobuf:"varint,1,opt,name=min_liquidation_factor,json=minLiquidationFactor,proto3" json:"min_liquidation_factor,omitempty"`
	// liquidation bonus factor permille
	LiquidationBonusFactor uint32 `protobuf:"varint,2,opt,name=liquidation_bonus_factor,json=liquidationBonusFactor,proto3" json:"liquidation_bonus_factor,omitempty"`
	// protocol liquidation fee factor permille
	ProtocolLiquidationFeeFactor uint32 `protobuf:"varint,3,opt,name=protocol_liquidation_fee_factor,json=protocolLiquidationFeeFactor,proto3" json:"protocol_liquidation_fee_factor,omitempty"`
	// protocol liquidation fee collector
	ProtocolLiquidationFeeCollector string `protobuf:"bytes,4,opt,name=protocol_liquidation_fee_collector,json=protocolLiquidationFeeCollector,proto3" json:"protocol_liquidation_fee_collector,omitempty"`
}

func (m *Params) Reset()         { *m = Params{} }
func (m *Params) String() string { return proto.CompactTextString(m) }
func (*Params) ProtoMessage()    {}
func (*Params) Descriptor() ([]byte, []int) {
	return fileDescriptor_e5694df60cc4d04a, []int{0}
}
func (m *Params) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Params.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Params) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Params.Merge(m, src)
}
func (m *Params) XXX_Size() int {
	return m.Size()
}
func (m *Params) XXX_DiscardUnknown() {
	xxx_messageInfo_Params.DiscardUnknown(m)
}

var xxx_messageInfo_Params proto.InternalMessageInfo

func (m *Params) GetMinLiquidationFactor() uint32 {
	if m != nil {
		return m.MinLiquidationFactor
	}
	return 0
}

func (m *Params) GetLiquidationBonusFactor() uint32 {
	if m != nil {
		return m.LiquidationBonusFactor
	}
	return 0
}

func (m *Params) GetProtocolLiquidationFeeFactor() uint32 {
	if m != nil {
		return m.ProtocolLiquidationFeeFactor
	}
	return 0
}

func (m *Params) GetProtocolLiquidationFeeCollector() string {
	if m != nil {
		return m.ProtocolLiquidationFeeCollector
	}
	return ""
}

func init() {
	proto.RegisterType((*Params)(nil), "bitway.liquidation.Params")
}

func init() { proto.RegisterFile("bitway/liquidation/params.proto", fileDescriptor_e5694df60cc4d04a) }

var fileDescriptor_e5694df60cc4d04a = []byte{
	// 258 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x4f, 0xca, 0x2c, 0x29,
	0x4f, 0xac, 0xd4, 0xcf, 0xc9, 0x2c, 0x2c, 0xcd, 0x4c, 0x49, 0x2c, 0xc9, 0xcc, 0xcf, 0xd3, 0x2f,
	0x48, 0x2c, 0x4a, 0xcc, 0x2d, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x12, 0x82, 0x28, 0xd0,
	0x43, 0x52, 0x20, 0x25, 0x92, 0x9e, 0x9f, 0x9e, 0x0f, 0x96, 0xd6, 0x07, 0xb1, 0x20, 0x2a, 0x95,
	0x7a, 0x98, 0xb8, 0xd8, 0x02, 0xc0, 0x5a, 0x85, 0x4c, 0xb8, 0xc4, 0x72, 0x33, 0xf3, 0xe2, 0x91,
	0xf4, 0xc4, 0xa7, 0x25, 0x26, 0x97, 0xe4, 0x17, 0x49, 0x30, 0x2a, 0x30, 0x6a, 0xf0, 0x06, 0x89,
	0xe4, 0x66, 0xe6, 0xf9, 0x20, 0x24, 0xdd, 0xc0, 0x72, 0x42, 0x16, 0x5c, 0x12, 0xc8, 0x3a, 0x92,
	0xf2, 0xf3, 0x4a, 0x8b, 0x61, 0xfa, 0x98, 0xc0, 0xfa, 0xc4, 0x90, 0xe4, 0x9d, 0x40, 0xd2, 0x50,
	0x9d, 0xae, 0x5c, 0xf2, 0x60, 0x37, 0x24, 0xe7, 0xe7, 0xa0, 0x5a, 0x9a, 0x9a, 0x0a, 0x33, 0x80,
	0x19, 0x6c, 0x80, 0x0c, 0x4c, 0x19, 0xb2, 0xed, 0xa9, 0xa9, 0x50, 0x63, 0xbc, 0xb9, 0x94, 0x70,
	0x1a, 0x93, 0x9c, 0x9f, 0x93, 0x93, 0x0a, 0x36, 0x89, 0x45, 0x81, 0x51, 0x83, 0x33, 0x48, 0x1e,
	0xbb, 0x49, 0xce, 0x30, 0x65, 0x4e, 0x5e, 0x27, 0x1e, 0xc9, 0x31, 0x5e, 0x78, 0x24, 0xc7, 0xf8,
	0xe0, 0x91, 0x1c, 0xe3, 0x84, 0xc7, 0x72, 0x0c, 0x17, 0x1e, 0xcb, 0x31, 0xdc, 0x78, 0x2c, 0xc7,
	0x10, 0x65, 0x90, 0x9e, 0x59, 0x92, 0x51, 0x9a, 0xa4, 0x97, 0x9c, 0x9f, 0xab, 0x0f, 0x09, 0xdd,
	0x9c, 0xc4, 0xa4, 0x62, 0x28, 0x53, 0xbf, 0x02, 0x25, 0x2e, 0x4a, 0x2a, 0x0b, 0x52, 0x8b, 0x93,
	0xd8, 0xc0, 0x96, 0x19, 0x03, 0x02, 0x00, 0x00, 0xff, 0xff, 0xa4, 0xf0, 0x3d, 0xa2, 0xae, 0x01,
	0x00, 0x00,
}

func (m *Params) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Params) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Params) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.ProtocolLiquidationFeeCollector) > 0 {
		i -= len(m.ProtocolLiquidationFeeCollector)
		copy(dAtA[i:], m.ProtocolLiquidationFeeCollector)
		i = encodeVarintParams(dAtA, i, uint64(len(m.ProtocolLiquidationFeeCollector)))
		i--
		dAtA[i] = 0x22
	}
	if m.ProtocolLiquidationFeeFactor != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.ProtocolLiquidationFeeFactor))
		i--
		dAtA[i] = 0x18
	}
	if m.LiquidationBonusFactor != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.LiquidationBonusFactor))
		i--
		dAtA[i] = 0x10
	}
	if m.MinLiquidationFactor != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.MinLiquidationFactor))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintParams(dAtA []byte, offset int, v uint64) int {
	offset -= sovParams(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Params) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.MinLiquidationFactor != 0 {
		n += 1 + sovParams(uint64(m.MinLiquidationFactor))
	}
	if m.LiquidationBonusFactor != 0 {
		n += 1 + sovParams(uint64(m.LiquidationBonusFactor))
	}
	if m.ProtocolLiquidationFeeFactor != 0 {
		n += 1 + sovParams(uint64(m.ProtocolLiquidationFeeFactor))
	}
	l = len(m.ProtocolLiquidationFeeCollector)
	if l > 0 {
		n += 1 + l + sovParams(uint64(l))
	}
	return n
}

func sovParams(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozParams(x uint64) (n int) {
	return sovParams(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Params) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowParams
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Params: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Params: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MinLiquidationFactor", wireType)
			}
			m.MinLiquidationFactor = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MinLiquidationFactor |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field LiquidationBonusFactor", wireType)
			}
			m.LiquidationBonusFactor = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.LiquidationBonusFactor |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ProtocolLiquidationFeeFactor", wireType)
			}
			m.ProtocolLiquidationFeeFactor = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ProtocolLiquidationFeeFactor |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ProtocolLiquidationFeeCollector", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ProtocolLiquidationFeeCollector = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipParams(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthParams
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipParams(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowParams
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthParams
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupParams
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthParams
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthParams        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowParams          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupParams = fmt.Errorf("proto: unexpected end of group")
)
