// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: bitway/lending/params.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	github_com_cosmos_gogoproto_types "github.com/cosmos/gogoproto/types"
	_ "google.golang.org/protobuf/types/known/durationpb"
	io "io"
	math "math"
	math_bits "math/bits"
	time "time"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = time.Kitchen

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Params defines the parameters for the module.
type Params struct {
	// final timeout duration for loan
	FinalTimeoutDuration time.Duration `protobuf:"bytes,1,opt,name=final_timeout_duration,json=finalTimeoutDuration,proto3,stdduration" json:"final_timeout_duration"`
	// maximum fee rate multiplier for liquidation; 0 means no limit
	MaxLiquidationFeeRateMultiplier int64 `protobuf:"varint,2,opt,name=max_liquidation_fee_rate_multiplier,json=maxLiquidationFeeRateMultiplier,proto3" json:"max_liquidation_fee_rate_multiplier,omitempty"`
	// request fee collector address
	RequestFeeCollector string `protobuf:"bytes,3,opt,name=request_fee_collector,json=requestFeeCollector,proto3" json:"request_fee_collector,omitempty"`
	// origination fee collector address
	OriginationFeeCollector string `protobuf:"bytes,4,opt,name=origination_fee_collector,json=originationFeeCollector,proto3" json:"origination_fee_collector,omitempty"`
	// protocol fee collector address
	ProtocolFeeCollector string `protobuf:"bytes,5,opt,name=protocol_fee_collector,json=protocolFeeCollector,proto3" json:"protocol_fee_collector,omitempty"`
}

func (m *Params) Reset()         { *m = Params{} }
func (m *Params) String() string { return proto.CompactTextString(m) }
func (*Params) ProtoMessage()    {}
func (*Params) Descriptor() ([]byte, []int) {
	return fileDescriptor_5b34cb91c8a05006, []int{0}
}
func (m *Params) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Params.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Params) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Params.Merge(m, src)
}
func (m *Params) XXX_Size() int {
	return m.Size()
}
func (m *Params) XXX_DiscardUnknown() {
	xxx_messageInfo_Params.DiscardUnknown(m)
}

var xxx_messageInfo_Params proto.InternalMessageInfo

func (m *Params) GetFinalTimeoutDuration() time.Duration {
	if m != nil {
		return m.FinalTimeoutDuration
	}
	return 0
}

func (m *Params) GetMaxLiquidationFeeRateMultiplier() int64 {
	if m != nil {
		return m.MaxLiquidationFeeRateMultiplier
	}
	return 0
}

func (m *Params) GetRequestFeeCollector() string {
	if m != nil {
		return m.RequestFeeCollector
	}
	return ""
}

func (m *Params) GetOriginationFeeCollector() string {
	if m != nil {
		return m.OriginationFeeCollector
	}
	return ""
}

func (m *Params) GetProtocolFeeCollector() string {
	if m != nil {
		return m.ProtocolFeeCollector
	}
	return ""
}

func init() {
	proto.RegisterType((*Params)(nil), "bitway.lending.Params")
}

func init() { proto.RegisterFile("bitway/lending/params.proto", fileDescriptor_5b34cb91c8a05006) }

var fileDescriptor_5b34cb91c8a05006 = []byte{
	// 350 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x91, 0x41, 0x4f, 0xf2, 0x30,
	0x18, 0xc7, 0x57, 0x78, 0x5f, 0xf2, 0xbe, 0x33, 0xf1, 0x30, 0x11, 0x01, 0x93, 0x41, 0xf4, 0xc2,
	0xc1, 0xac, 0x09, 0x7a, 0xf2, 0x88, 0x86, 0x13, 0x26, 0x66, 0xf1, 0xa2, 0x97, 0xa5, 0x1b, 0x0f,
	0xb5, 0x49, 0xb7, 0x8e, 0xae, 0x8d, 0xf0, 0x2d, 0x3c, 0xfa, 0x91, 0x38, 0x72, 0xd3, 0x93, 0x1a,
	0xf8, 0x22, 0xc6, 0x6e, 0x03, 0xf4, 0xf6, 0xb4, 0xbf, 0xff, 0xff, 0xd7, 0x34, 0x8f, 0x7d, 0x1c,
	0x32, 0xf5, 0x44, 0xe6, 0x98, 0x43, 0x32, 0x66, 0x09, 0xc5, 0x29, 0x91, 0x24, 0xce, 0xbc, 0x54,
	0x0a, 0x25, 0x9c, 0xfd, 0x1c, 0x7a, 0x05, 0x6c, 0xd7, 0xa9, 0xa0, 0xc2, 0x20, 0xfc, 0x3d, 0xe5,
	0xa9, 0xb6, 0x4b, 0x85, 0xa0, 0x1c, 0xb0, 0x39, 0x85, 0x7a, 0x82, 0xc7, 0x5a, 0x12, 0xc5, 0x44,
	0x92, 0xf3, 0x93, 0xd7, 0x8a, 0x5d, 0xbb, 0x35, 0x5a, 0xe7, 0xde, 0x6e, 0x4c, 0x58, 0x42, 0x78,
	0xa0, 0x58, 0x0c, 0x42, 0xab, 0xa0, 0x8c, 0x36, 0x51, 0x17, 0xf5, 0xf6, 0xfa, 0x2d, 0x2f, 0x77,
	0x79, 0xa5, 0xcb, 0xbb, 0x2e, 0x02, 0x83, 0x7f, 0x8b, 0xf7, 0x8e, 0xf5, 0xf2, 0xd1, 0x41, 0x7e,
	0xdd, 0x28, 0xee, 0x72, 0x43, 0xc9, 0x9d, 0x91, 0x7d, 0x1a, 0x93, 0x59, 0xc0, 0xd9, 0x54, 0xb3,
	0xb1, 0xb9, 0x0a, 0x26, 0x00, 0x81, 0x24, 0x0a, 0x82, 0x58, 0x73, 0xc5, 0x52, 0xce, 0x40, 0x36,
	0x2b, 0x5d, 0xd4, 0xab, 0xfa, 0x9d, 0x98, 0xcc, 0x46, 0xdb, 0xe4, 0x10, 0xc0, 0x27, 0x0a, 0x6e,
	0x36, 0x31, 0xa7, 0x6f, 0x1f, 0x4a, 0x98, 0x6a, 0xc8, 0x94, 0xb1, 0x44, 0x82, 0x73, 0x88, 0x94,
	0x90, 0xcd, 0x6a, 0x17, 0xf5, 0xfe, 0xfb, 0x07, 0x05, 0x1c, 0x02, 0x5c, 0x95, 0xc8, 0xb9, 0xb4,
	0x5b, 0x42, 0x32, 0xca, 0x92, 0xed, 0xeb, 0xdb, 0xde, 0x1f, 0xd3, 0x3b, 0xda, 0x09, 0xfc, 0xe8,
	0x5e, 0xd8, 0x0d, 0xf3, 0xe5, 0x48, 0xf0, 0x5f, 0xc5, 0xbf, 0xa6, 0x58, 0x2f, 0xe9, 0x6e, 0x6b,
	0x30, 0x5c, 0xac, 0x5c, 0xb4, 0x5c, 0xb9, 0xe8, 0x73, 0xe5, 0xa2, 0xe7, 0xb5, 0x6b, 0x2d, 0xd7,
	0xae, 0xf5, 0xb6, 0x76, 0xad, 0x87, 0x33, 0xca, 0xd4, 0xa3, 0x0e, 0xbd, 0x48, 0xc4, 0x38, 0x5f,
	0x22, 0x27, 0x61, 0x56, 0x8c, 0x78, 0xb6, 0x59, 0xb7, 0x9a, 0xa7, 0x90, 0x85, 0x35, 0x63, 0x3f,
	0xff, 0x0a, 0x00, 0x00, 0xff, 0xff, 0xf8, 0x2c, 0x04, 0x14, 0x0d, 0x02, 0x00, 0x00,
}

func (m *Params) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Params) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Params) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.ProtocolFeeCollector) > 0 {
		i -= len(m.ProtocolFeeCollector)
		copy(dAtA[i:], m.ProtocolFeeCollector)
		i = encodeVarintParams(dAtA, i, uint64(len(m.ProtocolFeeCollector)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.OriginationFeeCollector) > 0 {
		i -= len(m.OriginationFeeCollector)
		copy(dAtA[i:], m.OriginationFeeCollector)
		i = encodeVarintParams(dAtA, i, uint64(len(m.OriginationFeeCollector)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.RequestFeeCollector) > 0 {
		i -= len(m.RequestFeeCollector)
		copy(dAtA[i:], m.RequestFeeCollector)
		i = encodeVarintParams(dAtA, i, uint64(len(m.RequestFeeCollector)))
		i--
		dAtA[i] = 0x1a
	}
	if m.MaxLiquidationFeeRateMultiplier != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.MaxLiquidationFeeRateMultiplier))
		i--
		dAtA[i] = 0x10
	}
	n1, err1 := github_com_cosmos_gogoproto_types.StdDurationMarshalTo(m.FinalTimeoutDuration, dAtA[i-github_com_cosmos_gogoproto_types.SizeOfStdDuration(m.FinalTimeoutDuration):])
	if err1 != nil {
		return 0, err1
	}
	i -= n1
	i = encodeVarintParams(dAtA, i, uint64(n1))
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func encodeVarintParams(dAtA []byte, offset int, v uint64) int {
	offset -= sovParams(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Params) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = github_com_cosmos_gogoproto_types.SizeOfStdDuration(m.FinalTimeoutDuration)
	n += 1 + l + sovParams(uint64(l))
	if m.MaxLiquidationFeeRateMultiplier != 0 {
		n += 1 + sovParams(uint64(m.MaxLiquidationFeeRateMultiplier))
	}
	l = len(m.RequestFeeCollector)
	if l > 0 {
		n += 1 + l + sovParams(uint64(l))
	}
	l = len(m.OriginationFeeCollector)
	if l > 0 {
		n += 1 + l + sovParams(uint64(l))
	}
	l = len(m.ProtocolFeeCollector)
	if l > 0 {
		n += 1 + l + sovParams(uint64(l))
	}
	return n
}

func sovParams(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozParams(x uint64) (n int) {
	return sovParams(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Params) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowParams
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Params: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Params: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FinalTimeoutDuration", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_cosmos_gogoproto_types.StdDurationUnmarshal(&m.FinalTimeoutDuration, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxLiquidationFeeRateMultiplier", wireType)
			}
			m.MaxLiquidationFeeRateMultiplier = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxLiquidationFeeRateMultiplier |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RequestFeeCollector", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RequestFeeCollector = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OriginationFeeCollector", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.OriginationFeeCollector = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ProtocolFeeCollector", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ProtocolFeeCollector = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipParams(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthParams
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipParams(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowParams
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthParams
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupParams
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthParams
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthParams        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowParams          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupParams = fmt.Errorf("proto: unexpected end of group")
)
